---
name: Actions file for shell script
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Runs shell script
        run: |
          pwd
        shell: bash
